// <auto-generated />
using BattleCatsEntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleCatsEntityFramework.Migrations
{
    [DbContext(typeof(BattleCatsContext))]
    partial class BattleCatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BattleCatsEntityFramework.Models.BattleCatsCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attitude")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChonkRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fluffiness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialAttack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialAttackPower")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BattleCatsCards");
                });

            modelBuilder.Entity("BattleCatsEntityFramework.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BattleCatsEntityFramework.Models.UserCard", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("UserCards");
                });

            modelBuilder.Entity("BattleCatsEntityFramework.Models.UserCard", b =>
                {
                    b.HasOne("BattleCatsEntityFramework.Models.BattleCatsCard", "Card")
                        .WithMany("UserCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleCatsEntityFramework.Models.User", "User")
                        .WithMany("UserCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BattleCatsEntityFramework.Models.BattleCatsCard", b =>
                {
                    b.Navigation("UserCards");
                });

            modelBuilder.Entity("BattleCatsEntityFramework.Models.User", b =>
                {
                    b.Navigation("UserCards");
                });
#pragma warning restore 612, 618
        }
    }
}
